(()=>{"use strict";
const c=document.getElementById("c"),x=c.getContext("2d"),techBtn=document.getElementById("techBtn"),domainBtn=document.getElementById("domainBtn"),charBtn=document.getElementById("charBtn"),charName=document.getElementById("charName"),modeLabel=document.getElementById("modeLabel"),cinema=document.getElementById("cinema"),cinemaName=document.getElementById("cinemaName");
let W=0,H=0,last=0,shake=0,time=0;
const key={left:false,right:false,block:false};
const roster=[
 {id:"vessel",name:"VESSEL",domain:"MALEVOLENT SHRINELESS",accent:"#d9829b",ct:"SLASH"},
 {id:"honored",name:"HONORED ONE",domain:"INFINITE HORIZON",accent:"#dff7ff",ct:"LIMITLESS"},
 {id:"shadow",name:"SHADOW MANIPULATOR",domain:"CHIMERA SHADOW GARDEN",accent:"#20242f",ct:"TEN SHADOWS"}
];
let charIndex=0;
const p={x:220,y:0,vx:0,vy:0,face:1,hp:100,ce:100,aw:0,on:true,attack:0,attackMax:.3,combo:0,comboT:0,dash:0,dashMax:.42,block:false,blockBlend:0,awakened:false,awFlash:0,land:0,techAnim:0,techMax:.65,domainAnim:0,domainActive:0,domainMax:1.8,hitstop:0};
const e={x:700,y:0,vx:0,vy:0,hp:100,on:true,hit:0};
const fx=[];
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const ease=t=>t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;
const q30=t=>Math.floor(t*30)/30;
function ground(){return H*.78}
function resize(){const r=c.getBoundingClientRect();W=c.width=Math.max(1,r.width*devicePixelRatio);H=c.height=Math.max(1,r.height*devicePixelRatio);x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);W=r.width;H=r.height;p.x=Math.min(p.x,W*.42);e.x=Math.max(W*.62,Math.min(e.x,W-55));p.y=e.y=ground()}
addEventListener("resize",resize);resize();
function particle(px,py,vx,vy,l=.3,type="ce"){fx.push({x:px,y:py,vx,vy,l,max:l,type})}
function burst(px,py,n=14,type="ce"){for(let i=0;i<n;i++){let a=Math.random()*6.28,s=60+Math.random()*260;particle(px,py,Math.cos(a)*s,Math.sin(a)*s,.2+Math.random()*.25,type)}}
function flash(){const f=document.getElementById("impact");f.classList.remove("flash");void f.offsetWidth;f.classList.add("flash")}
function hitEnemy(dmg,pow){if(Math.abs(p.x-e.x)<125&&Math.abs(p.y-e.y)<95&&e.hit<=0){e.hp=Math.max(0,e.hp-dmg);e.vx=p.face*pow;e.vy=-pow*.2;e.hit=.24;p.aw=Math.min(100,p.aw+dmg*1.65);p.hitstop=.055;shake=dmg>12?13:7;burst(e.x,e.y-55,dmg>12?24:13,dmg>12?"slash":"hit");flash()}}
function attack(){if(p.attack>0||p.techAnim>0||p.domainAnim>0||p.block)return;p.combo=p.comboT>0?(p.combo%4)+1:1;p.comboT=.52;p.attackMax=p.combo===4?.42:.31;p.attack=p.attackMax;setTimeout(()=>{if(p.attack>0)hitEnemy(p.combo===4?14:7,p.combo===4?520:270)},Math.round((p.combo===4?.18:.12)*1000))}
function awaken(){if(p.aw<100||p.awakened)return;p.awakened=true;p.awFlash=.85;shake=16;burst(p.x,p.y-55,44,"aw");flash()}
function tech(){if(!p.awakened){if(p.aw>=100)awaken();return}if(p.ce<25||p.attack>0||p.techAnim>0||p.domainAnim>0||p.block)return;p.ce-=25;p.techMax=.72;p.techAnim=p.techMax;const id=roster[charIndex].id;setTimeout(()=>{if(p.techAnim<=0)return;if(id==="vessel"){hitEnemy(18,620);for(let i=0;i<30;i++)particle(p.x+p.face*(55+Math.random()*175),p.y-25-Math.random()*115,p.face*(170+Math.random()*380),(Math.random()-.5)*290,.42,"slash")}else if(id==="honored"){if(Math.abs(p.x-e.x)<280){hitEnemy(16,500);burst(e.x,e.y-55,34,"blue")}}else{if(Math.abs(p.x-e.x)<240){hitEnemy(15,450);for(let i=0;i<26;i++)particle(e.x+(Math.random()-.5)*90,e.y-8,0,-120-Math.random()*220,.5,"shadow")}}},260)}
function startDomain(){if(!p.awakened||p.ce<80||p.domainAnim>0||p.domainActive>0)return;p.ce-=80;p.domainAnim=p.domainMax;p.vx=0;shake=8;cinemaName.textContent=roster[charIndex].domain;cinema.classList.add("show");setTimeout(()=>flash(),520);setTimeout(()=>{if(p.domainAnim>0){p.domainActive=7;burst(p.x,p.y-60,70,"domain");shake=20}},1180)}
function cycleChar(){if(p.domainAnim>0)return;charIndex=(charIndex+1)%roster.length;p.aw=0;p.awakened=false;p.ce=100;p.domainActive=0;p.techAnim=0;p.attack=0;charName.textContent=roster[charIndex].name;burst(p.x,p.y-55,20,"switch")}
function jump(){if(p.on&&!p.block&&p.domainAnim<=0){p.vy=-620;p.on=false;p.land=0}}
function dash(){if(p.dash<=0&&!p.block&&p.domainAnim<=0){p.vx=p.face*790;p.dashMax=.44;p.dash=p.dashMax;burst(p.x-p.face*12,p.y-24,12,"dust")}}
function action(a){if(a==="jump")jump();if(a==="attack")attack();if(a==="tech")tech();if(a==="domain")startDomain();if(a==="char")cycleChar();if(a==="dash")dash();if(a==="block")p.block=true}
document.querySelectorAll("[data-hold]").forEach(b=>{const k=b.dataset.hold;b.onpointerdown=q=>{q.preventDefault();key[k]=true};b.onpointerup=b.onpointercancel=()=>key[k]=false});
document.querySelectorAll("[data-action]").forEach(b=>{b.onpointerdown=q=>{q.preventDefault();action(b.dataset.action)};b.onpointerup=b.onpointercancel=()=>{if(b.dataset.action==="block")p.block=false}});
addEventListener("keydown",q=>{if(q.repeat)return;if(q.key==="a"||q.key==="ArrowLeft")key.left=true;if(q.key==="d"||q.key==="ArrowRight")key.right=true;if(q.key==="w"||q.key==="ArrowUp")jump();if(q.key==="j")attack();if(q.key==="k")tech();if(q.key==="u")startDomain();if(q.key==="c")cycleChar();if(q.key==="Shift")dash();if(q.key==="l")p.block=true});
addEventListener("keyup",q=>{if(q.key==="a"||q.key==="ArrowLeft")key.left=false;if(q.key==="d"||q.key==="ArrowRight")key.right=false;if(q.key==="l")p.block=false});
function physics(o,dt){const was=o.on;o.vy+=1500*dt;o.x+=o.vx*dt;o.y+=o.vy*dt;o.vx*=Math.pow(.0015,dt);if(o.y>=ground()){o.y=ground();o.vy=0;o.on=true;if(!was&&o===p){p.land=.18;burst(p.x,p.y,7,"dust")}}o.x=Math.max(45,Math.min(W-45,o.x))}
function limb(ax,ay,bx,by,cx,cy,w=7,col="#101114"){x.beginPath();x.moveTo(ax,ay);x.lineTo(bx,by);x.lineTo(cx,cy);x.strokeStyle=col;x.lineWidth=w;x.stroke()}
function poseBase(o){const dir=o.face,run=Math.min(1,Math.abs(o.vx)/260),phase=q30(time)*12,step=Math.sin(phase)*run;let z={bodyX:0,bodyY:-55,headY:-84,la:[-dir*15,-43,-dir*25,-27],ra:[dir*15,-43,dir*27,-28],ll:[-12,-18,-18,0],rl:[12,-18,20,0],rot:0};
 if(run>.1&&o.on&&o.attack<=0&&o.techAnim<=0){z.bodyX=dir*(3+2*Math.sin(phase*2));z.bodyY=-55+Math.abs(Math.sin(phase))*2;z.ll=[-dir*step*13,-17,dir*step*24,0];z.rl=[dir*step*13,-17,-dir*step*24,0];z.la=[-dir*15,-45,dir*step*18,-28];z.ra=[dir*15,-45,-dir*step*18,-28]}
 if(!o.on){z.bodyY=-58;z.headY=-88;z.ll=[-13,-22,-25,-5];z.rl=[13,-22,28,-10];z.la=[-dir*14,-48,-dir*28,-33];z.ra=[dir*14,-48,dir*30,-38]}
 if(o.land>0){const t=1-o.land/.18,s=Math.sin(t*Math.PI);z.bodyY=-55+9*s;z.headY=-84+7*s;z.ll=[-15,-16,-29,0];z.rl=[15,-16,29,0]}
 const bb=o.blockBlend;if(bb>.01){const t=ease(bb);z.bodyX=-dir*5*t;z.la=[-dir*(10-3*t),-48,dir*(2+18*t),-40-29*t];z.ra=[dir*9,-48,dir*(20+8*t),-35-22*t]}
 if(o.dash>0){const t=1-o.dash/o.dashMax,s=Math.sin(Math.min(1,t*2)*Math.PI/2);z.bodyX=dir*(7+10*s);z.headY=-82;z.rot=dir*.06;z.la=[-dir*8,-48,-dir*(18+18*s),-30];z.ra=[dir*8,-48,-dir*(12+18*s),-24];z.ll=[-10,-18,-dir*(12+16*s),0];z.rl=[10,-18,dir*(20+12*s),0]}
 if(o.attack>0){const t=q30(1-o.attack/o.attackMax),n=o.combo||1,a=clamp(t/.25),b=clamp((t-.25)/.38),r=clamp((t-.72)/.28);const ext=Math.sin(clamp(b)*Math.PI)*58;if(n===1)z.ra=[dir*12,-46,dir*(18+ext),-43];if(n===2)z.la=[-dir*12,-46,dir*(12+ext),-55];if(n===3){z.ra=[dir*12,-45,dir*(18+ext*.75),-26];z.bodyX=dir*7*b}if(n===4){z.ra=[dir*12,-47,dir*(20+ext),-65];z.ll=[-10,-18,-dir*18,0];z.rl=[10,-18,dir*(18+ext*.35),-9]}z.rot=dir*(a*.03-b*.05+r*.02)}
 if(o.techAnim>0){const t=q30(1-o.techAnim/o.techMax),cast=ease(clamp((t-.12)/.48));z.bodyX=-dir*6+dir*10*cast;z.ra=[dir*10,-48,dir*(18+28*cast),-60+18*cast];z.la=[-dir*10,-48,-dir*(18+10*cast),-62+10*cast];z.rot=-dir*.04+dir*.08*cast}
 if(o.domainAnim>0){const t=q30(1-o.domainAnim/o.domainMax);z.bodyY=-57;z.headY=-88;z.la=[-dir*8,-48,-6,-66];z.ra=[dir*8,-48,6,-66];z.ll=[-13,-18,-22,0];z.rl=[13,-18,22,0];z.rot=Math.sin(t*18)*.01}
 return z}
function drawHair(id,bx,hy,dir){if(id==="vessel"){x.fillStyle="#d9829b";x.strokeStyle="#151519";x.lineWidth=2;x.beginPath();x.moveTo(bx-17,hy-6);x.lineTo(bx-24,hy-22);x.lineTo(bx-11,hy-18);x.lineTo(bx-8,hy-31);x.lineTo(bx+1,hy-20);x.lineTo(bx+9,hy-31);x.lineTo(bx+12,hy-17);x.lineTo(bx+25,hy-20);x.lineTo(bx+17,hy-5);x.quadraticCurveTo(bx,hy-13,bx-17,hy-6);x.fill();x.stroke()}
 else if(id==="honored"){x.fillStyle="#f3fbff";x.strokeStyle="#151519";x.lineWidth=2;x.beginPath();x.moveTo(bx-19,hy-5);x.lineTo(bx-25,hy-20);x.lineTo(bx-12,hy-18);x.lineTo(bx-8,hy-32);x.lineTo(bx,hy-22);x.lineTo(bx+8,hy-34);x.lineTo(bx+12,hy-19);x.lineTo(bx+25,hy-23);x.lineTo(bx+18,hy-5);x.closePath();x.fill();x.stroke();x.fillStyle="#0c0d10";x.fillRect(bx-18,hy-3,36,8)}
 else{x.fillStyle="#11131a";x.strokeStyle="#050609";x.lineWidth=2;x.beginPath();for(let i=0;i<12;i++){const a=-Math.PI+i*Math.PI/11,r=i%2?24:34;x.lineTo(bx+Math.cos(a)*r,hy-10+Math.sin(a)*r)}x.lineTo(bx+18,hy+1);x.lineTo(bx-18,hy+1);x.closePath();x.fill();x.stroke()}}
function fighter(o){const id=roster[charIndex].id,z=poseBase(o),dir=o.face;x.save();x.translate(o.x,o.y);x.rotate(z.rot);x.lineCap="round";x.lineJoin="round";
 if(o.domainActive>0){x.strokeStyle=roster[charIndex].accent;x.globalAlpha=.18+.08*Math.sin(time*10);x.lineWidth=3;x.beginPath();x.arc(0,-55,50+Math.sin(time*6)*5,0,6.28);x.stroke();x.globalAlpha=1}
 if(id==="vessel"){x.strokeStyle="#a7192d";x.lineWidth=9;x.beginPath();x.moveTo(-13+z.bodyX,z.bodyY-5);x.lineTo(z.bodyX,z.bodyY+5);x.lineTo(14+z.bodyX,z.bodyY-5);x.stroke()}
 if(id==="honored"){x.strokeStyle="#111217";x.lineWidth=12;x.beginPath();x.moveTo(z.bodyX,z.bodyY);x.lineTo(z.bodyX,-19);x.stroke()}
 else{x.strokeStyle=id==="shadow"?"#151a24":"#101114";x.lineWidth=9;x.beginPath();x.moveTo(z.bodyX,z.bodyY);x.lineTo(z.bodyX,-20);x.stroke()}
 limb(z.bodyX,-49,z.la[0]+z.bodyX,z.la[1],z.la[2]+z.bodyX,z.la[3],7,id==="shadow"?"#151a24":"#101114");limb(z.bodyX,-49,z.ra[0]+z.bodyX,z.ra[1],z.ra[2]+z.bodyX,z.ra[3],7,id==="shadow"?"#151a24":"#101114");limb(z.bodyX,-20,z.ll[0]+z.bodyX,z.ll[1],z.ll[2]+z.bodyX,z.ll[3],7,id==="shadow"?"#151a24":"#101114");limb(z.bodyX,-20,z.rl[0]+z.bodyX,z.rl[1],z.rl[2]+z.bodyX,z.rl[3],7,id==="shadow"?"#151a24":"#101114");
 x.fillStyle="#e7c5b4";x.beginPath();x.arc(z.bodyX,z.headY,18,0,6.28);x.fill();x.strokeStyle="#101114";x.lineWidth=3;x.stroke();drawHair(id,z.bodyX,z.headY,dir);
 if(id!=="honored"){x.fillStyle="#111";x.fillRect(z.bodyX+dir*4,z.headY-2,3,2)}
 if(o.blockBlend>.1){x.strokeStyle="#fff";x.globalAlpha=.32;o===p&&(x.globalAlpha=.38);x.lineWidth=2;x.beginPath();x.arc(dir*24,-49,31,-1.1,1.1);x.stroke();x.globalAlpha=1}
 if(o.techAnim>0){const t=1-o.techAnim/o.techMax;if(id==="honored"){x.strokeStyle="#45b9ff";x.lineWidth=4;x.globalAlpha=clamp(t*2);x.beginPath();x.arc(dir*44,-48,10+22*t,0,6.28);x.stroke();x.globalAlpha=1}else if(id==="shadow"){x.fillStyle="#050609aa";x.beginPath();x.ellipse(0,2,25+55*t,7+15*t,0,0,6.28);x.fill()}else{x.strokeStyle="#e7e7ff";x.lineWidth=4;x.beginPath();x.moveTo(dir*18,-64);x.lineTo(dir*(35+70*t),-35);x.stroke()}}
 x.restore()}
function dummy(o){x.save();x.translate(o.x,o.y);x.lineCap="round";x.strokeStyle=o.hit>0?"#555":"#171717";x.lineWidth=7;const recoil=o.hit>0?Math.sin(o.hit*28)*13:0;x.rotate(recoil*.012);x.beginPath();x.arc(0,-82,18,0,6.28);x.moveTo(0,-64);x.lineTo(recoil,-20);x.moveTo(recoil,-20);x.lineTo(-19,0);x.moveTo(recoil,-20);x.lineTo(22,0);x.moveTo(0,-54);x.lineTo(-24,-34);x.moveTo(0,-54);x.lineTo(24,-34);x.stroke();x.restore()}
function drawStage(){if(p.domainActive>0){const id=roster[charIndex].id;if(id==="honored"){let g=x.createRadialGradient(W/2,H*.42,20,W/2,H*.42,Math.max(W,H));g.addColorStop(0,"#eafcff");g.addColorStop(.3,"#66b9ff");g.addColorStop(1,"#040711");x.fillStyle=g;x.fillRect(0,0,W,H);for(let i=0;i<80;i++){x.fillStyle="#ffffff"+((i%5)+3);x.fillRect((i*97+time*15)%W,(i*53)%H,2,2)}}else if(id==="shadow"){x.fillStyle="#05070c";x.fillRect(0,0,W,H);x.fillStyle="#111827";for(let i=0;i<12;i++){x.beginPath();x.ellipse((i*91)%W,ground()+10,70,18,0,0,6.28);x.fill()}}else{x.fillStyle="#17080b";x.fillRect(0,0,W,H);x.strokeStyle="#50151d";for(let i=0;i<W;i+=65){x.beginPath();x.moveTo(i,0);x.lineTo(i+80,H);x.stroke()}}x.fillStyle="#111";x.fillRect(0,ground()+2,W,3);return}
 let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,"#d8dadd");g.addColorStop(.56,"#b9bcc0");g.addColorStop(.57,"#85898e");g.addColorStop(1,"#65696e");x.fillStyle=g;x.fillRect(0,0,W,H);x.strokeStyle="#a9acb0";x.lineWidth=1;for(let i=0;i<W;i+=80){x.beginPath();x.moveTo(i,0);x.lineTo(i,H*.56);x.stroke()}x.strokeStyle="#5d6166";for(let y=H*.62;y<H;y+=45){x.beginPath();x.moveTo(0,y);x.lineTo(W,y);x.stroke()}x.fillStyle="#4d5054";x.fillRect(0,ground()+2,W,3)}
function drawDomainOpening(){if(p.domainAnim<=0)return;const t=1-p.domainAnim/p.domainMax,qt=q30(t);x.save();x.fillStyle="rgba(0,0,0,"+clamp(qt*1.8,0,.75)+")";x.fillRect(0,0,W,H);const cx=p.x,cy=p.y-58;if(qt>.18){x.strokeStyle=roster[charIndex].accent;x.lineWidth=3+qt*8;x.globalAlpha=.7;x.beginPath();x.arc(cx,cy,35+qt*Math.max(W,H)*.8,0,6.28);x.stroke()}if(qt>.45){x.globalAlpha=.22;x.fillStyle=roster[charIndex].accent;for(let i=0;i<9;i++){x.beginPath();x.arc(cx+Math.cos(i)*qt*120,cy+Math.sin(i*1.7)*qt*80,16+qt*18,0,6.28);x.fill()}}x.restore()}
function update(dt){time+=dt;if(p.hitstop>0){p.hitstop-=dt;return}const locked=p.domainAnim>0;const move=(key.right?1:0)-(key.left?1:0);if(move&&!p.block&&p.attack<=0&&p.techAnim<=0&&!locked){p.face=move;p.vx+=move*1800*dt}p.vx=Math.max(-340,Math.min(340,p.vx));p.block=key.block||p.block;p.blockBlend+=((p.block?1:0)-p.blockBlend)*Math.min(1,dt*18);p.attack=Math.max(0,p.attack-dt);p.comboT=Math.max(0,p.comboT-dt);p.dash=Math.max(0,p.dash-dt);p.land=Math.max(0,p.land-dt);p.awFlash=Math.max(0,p.awFlash-dt);p.techAnim=Math.max(0,p.techAnim-dt);p.domainAnim=Math.max(0,p.domainAnim-dt);p.domainActive=Math.max(0,p.domainActive-dt);e.hit=Math.max(0,e.hit-dt);p.ce=Math.min(100,p.ce+(p.awakened?6:9)*dt);physics(p,dt);physics(e,dt);
 if(p.domainAnim<=0)cinema.classList.remove("show");
 for(let i=fx.length-1;i>=0;i--){let f=fx[i];f.l-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.94;f.vy+=(f.type==="dust"?100:360)*dt;if(f.l<=0)fx.splice(i,1)}
 document.getElementById("pHP").style.width=p.hp+"%";document.getElementById("eHP").style.width=e.hp+"%";document.getElementById("ce").style.width=p.ce+"%";document.getElementById("aw").style.width=p.aw+"%";document.getElementById("ceText").textContent=Math.round(p.ce);document.getElementById("awText").textContent=p.awakened?"CT UNLOCKED":Math.round(p.aw)+"%";
 techBtn.className="tech "+(p.awakened?"active":p.aw>=100?"ready":"locked");techBtn.textContent=p.awakened?roster[charIndex].ct:p.aw>=100?"AWAKEN":"CT LOCKED";domainBtn.className="domain "+(p.domainActive>0?"active":p.awakened&&p.ce>=80?"ready":"");domainBtn.textContent=p.domainActive>0?"DOMAIN ACTIVE":"DOMAIN";charBtn.textContent=roster[(charIndex+1)%roster.length].name.split(" ")[0];modeLabel.textContent=p.domainActive>0?"DOMAIN":"TRAINING"}
function draw(){x.save();if(shake>.2){x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.82}drawStage();for(const f of fx){x.globalAlpha=Math.max(0,f.l/f.max);x.strokeStyle=f.type==="aw"?"#ed2445":f.type==="dust"?"#d7d7d7":f.type==="hit"?"#171717":f.type==="blue"?"#45b9ff":f.type==="shadow"?"#121722":f.type==="domain"?roster[charIndex].accent:"#6d46ff";x.lineWidth=f.type==="slash"?4:2;x.beginPath();x.moveTo(f.x,f.y);x.lineTo(f.x-f.vx*.035,f.y-f.vy*.035);x.stroke()}x.globalAlpha=1;fighter(p);dummy(e);drawDomainOpening();x.restore()}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();